# reference genome; note this is the prefix used during bwa indexing
ref: "data/zebraFinch/genome/Tgut_subseg_renamed.fa"
#ref: "data/BHduck/genome/MU014702.1.fa"

# location of fastq files; make sure the file path ends with a "/"! e.g. /n/home/files/
fastqDir: "data/zebraFinch/fastq/"
#fastqDir: "data/BHduck/fastq/"

# file suffixes for fastq and BAM files
fastq_suffix1: "_1.fastq.gz" # this is the suffix for the forward read
fastq_suffix2: "_2.fastq.gz" # this is the suffix for the reverse read
bam_suffix: "_dedup.bam" # the fastq2bam pipeline creates BAMs with names ending in "_dedup.bam". If you use BAMs from another workflow, change this accordingly (e.g. to just ".bam")

###
# These variables control the output of the fastq2bam workflow (please have forward slash follow name!)
###
fastq2bamDir: "fastq2bam/"      # this is the main directory
fastqFilterDir: "00_fastqFiltered/"
bamDir: "01_mappedReads/"
sumstatDir: "02_bamSumstats/"

# These variables control how the genome gets split into intervals according to Nmers in the reference genome
maxIntervalLen: 210000
maxBpPerList: 210000
maxIntervalsPerList: 200
minNmer: 100

###
# These variables control the output of the GATK4 workflow (please have forward slash follow name!)
###
gatkDir: "gatk/"
bamsForGatk: "fastq2bam/01_mappedReads/" # If you used the fastq2bam workflow above, simply specify that directory
gvcfDir: "01_gvcfs/"
dbDir: "02_genomicsDB/"
vcfDir_gatk: "03_vcfs/"
listDir: "lists/"

###
# These variables control the output of the FreeBayes workflow (please have forward slash follow name!)   
###
fbDir: "freebayes/"
bamsForFB: "fastq2bam/01_mappedReads/" # If you used the fastq2bam workflow above, simply specify that directory
intervalDir: "00_intervals/"
vcfDir_fb: "01_vcfs_byinterval/"
maxDP_fb: 200


#information for read groups
flowcell: "FLOWCELL"
platform: "ILLUMINA"

cluster_config: "profiles/slurm/cluster_config.yml"

