# reference genome; note this is the prefix used during bwa indexing
#ref: "data/zebraFinch/genome/Tgut_subseg_renamed.fa"
ref: "data/BHduck/genome/MU014702.1.fa"

# location of fastq files; make sure the file path ends with a "/"! e.g. /n/home/files/
fastqDir: "data/BHduck/fastq/"
# suffix of fastq files
fastq_suffix1: "_1.fastq.gz"
fastq_suffix2: "_2.fastq.gz"

# for same dir as snakemake pipeline, put ""
baseDir: ""

fastqFilterDir: "00_fastqFiltered/"
bamDir: "01_mappedReads/"
sumstatDir: "02_bamSumstats/"
gvcfDir: "03_gvcfs/"
dbDir: "04_genomicsDB/"
vcfDir: "05_vcfs/"

#listDir: "data/BHduck/lists/"
listDir: "lists/"
maxIntervalLen: 400000
maxBpPerList: 400000
maxIntervalsPerList: 200

#information for read groups
flowcell: "FLOWCELL"
platform: "ILLUMINA"

CLUSTER_JSON: "./cluster.json"
