__default__:
    partition: "holy-info"
    time: 5000
    nodes: 1
    output: "logs/slurm-%j.out"
    #error: "logs/slurm-%j.err"

###
# fastq2bam
###
fastp: 
    mem: 5000 
bwa_map: 
    nodes: 3
    mem: 15000 
sort_bam: 
    mem: 9000 
dedup: 
    mem: 9000 
bam_sumstats: 
    mem: 9000 


###
# bam2vcf_gatk
###

processRef: 
    time: 500
    nodes: 1
    mem: 5000 
bam2gvcf: 
    partition: "serial_requeue"
    nodes: 1
    mem: 30000 
gvcf2DB: 
    nodes: 1
    mem: 30000 
DB2vcf: 
    nodes: 1
    mem: 30000 
gatherVcfs: 
    nodes: 1
    mem: 10000 


###
# bam2vcf_fb
###

bam2vcf: 
    partition: "serial_requeue"
    #mem: 5000 # MEMORY IS SPECIFIED WITHIN RULE, TO INCREASE WITH ATTEMPTS
